# cloudbuild.yaml - FUCCART POC
steps:
  # Step 1: Build the project
  - name: 'maven:3.9.1-openjdk-25'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "===== Starting Build ====="
        cd "Documents/LITTProjectFolder/demo"
        mvn clean install

  # Step 2: Run unit tests
  - name: 'maven:3.9.1-openjdk-25'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "===== Running Unit Tests ====="
        cd "Documents/LITTProjectFolder/demo"
        mvn test

# Optional: store build artifacts in GCS (POC safe)
artifacts:
  objects:
    location: 'gs://fuccart-test-artifacts-demo/'
    paths:
      - 'Documents/LITTProjectFolder/demo/target/*.jar'
