steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a custom Dockerfile
        cat > Dockerfile.oraclejdk25 << 'EOF'
        FROM oraclelinux:9
        
        # Install Oracle JDK 25
        RUN dnf install -y oraclelinux-developer-release-el9 && \
            dnf install -y java-25-oracle-devel.x86_64
        
        # Install Maven
        RUN dnf install -y maven
        
        # Verify installations
        RUN java --version && mvn --version
        
        WORKDIR /workspace
        EOF
        
        # Build and use the image
        docker build -t oracle-jdk25-maven -f Dockerfile.oraclejdk25 .
        docker run -v $PWD:/workspace oracle-jdk25-maven mvn clean package
