steps:
  # Step 1: Build the project
  - name: 'maven:3.6.3-jdk-25'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building project..."
        mvn clean install

  # Step 2: Run unit tests
  - name: 'maven:3.6.3-jdk-25'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running tests..."
        mvn test

artifacts:
  objects:
    location: 'gs://fake-poc-artifacts/'  # Placeholder bucket (won’t actually deploy)
    paths:
      - 'target/*.jar'
